#!/bin/bash
#PBS -N reduction

#PBS -A wellman_flux
#PBS -q flux
#PBS -l qos=flux
#PBS -W group_list=wellman

#PBS -l walltime=06:00:00
#PBS -l nodes=1:ppn=1,pmem=4000mb

#PBS -e 16-analysis-20140912113545EDT-pbs.e
#PBS -o 16-analysis-20140912113545EDT-pbs.o

#PBS -M achintya@umich.edu
#PBS -m abe
#PBS -V
#PBS -W umask=0022

umask 0022

module load python/2.7.5
mkdir /tmp/${PBS_JOBID}
"cp -r /home/achint/projects/EGTA-personal/egtaonline3/temp/remote_path/GameAnalysis/* /tmp/${PBS_JOBID}"

cd /tmp/${PBS_JOBID}
export PYTHONPATH=$PYTHONPATH:/home/achint/projects/EGTA-personal/egtaonline3/temp/remote_path/GameAnalysis

python parseGame.py #{@game.id}-reduced-#{@time}.json 0 > #{@game.id}-reduced-#{@time}.txt
cp -r /tmp/${PBS_JOBID}/#{@game.id}-reduced-#{@time}.txt /home/achint/projects/EGTA-personal/egtaonline3/temp/remote_path/egtaonline/reduction/16/out
rm -rf /tmp/${PBS_JOBID}

